# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaMenu(object):
    def setupUi(self, TelaMenu):
        TelaMenu.setObjectName("TelaMenu")
        TelaMenu.resize(1421, 883)
        self.centralwidget = QtWidgets.QWidget(TelaMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCadastrarDesp = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrarDesp.setGeometry(QtCore.QRect(530, 160, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnCadastrarDesp.setFont(font)
        self.btnCadastrarDesp.setObjectName("btnCadastrarDesp")
        self.btnVerificarMes = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerificarMes.setGeometry(QtCore.QRect(530, 360, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnVerificarMes.setFont(font)
        self.btnVerificarMes.setObjectName("btnVerificarMes")
        self.btnVerificarSaldo = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerificarSaldo.setGeometry(QtCore.QRect(530, 460, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnVerificarSaldo.setFont(font)
        self.btnVerificarSaldo.setObjectName("btnVerificarSaldo")
        self.labelCadastro = QtWidgets.QLabel(self.centralwidget)
        self.labelCadastro.setGeometry(QtCore.QRect(650, 50, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.labelCadastro.setFont(font)
        self.labelCadastro.setObjectName("labelCadastro")
        self.btnSair = QtWidgets.QPushButton(self.centralwidget)
        self.btnSair.setGeometry(QtCore.QRect(600, 590, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnSair.setFont(font)
        self.btnSair.setObjectName("btnSair")
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(240, 590, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnVoltar.setFont(font)
        self.btnVoltar.setObjectName("btnVoltar")
        self.btnInserirReceita = QtWidgets.QPushButton(self.centralwidget)
        self.btnInserirReceita.setGeometry(QtCore.QRect(530, 260, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnInserirReceita.setFont(font)
        self.btnInserirReceita.setObjectName("btnInserirReceita")
        TelaMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TelaMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1421, 22))
        self.menubar.setObjectName("menubar")
        TelaMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TelaMenu)
        self.statusbar.setObjectName("statusbar")
        TelaMenu.setStatusBar(self.statusbar)

        self.retranslateUi(TelaMenu)
        QtCore.QMetaObject.connectSlotsByName(TelaMenu)

    def retranslateUi(self, TelaMenu):
        _translate = QtCore.QCoreApplication.translate
        TelaMenu.setWindowTitle(_translate("TelaMenu", "MainWindow"))
        self.btnCadastrarDesp.setText(_translate("TelaMenu", "Cadastrar despesas"))
        self.btnVerificarMes.setText(_translate("TelaMenu", "Verificar despesas"))
        self.btnVerificarSaldo.setText(_translate("TelaMenu", "Verificar saldo"))
        self.labelCadastro.setText(_translate("TelaMenu", "Menu"))
        self.btnSair.setText(_translate("TelaMenu", "Sair"))
        self.btnVoltar.setText(_translate("TelaMenu", "Voltar"))
        self.btnInserirReceita.setText(_translate("TelaMenu", "Inserir receita"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaMenu = QtWidgets.QMainWindow()
    ui = TelaMenu()
    ui.setupUi(TelaMenu)
    TelaMenu.show()
    sys.exit(app.exec_())
